name: Node.js CI and Docker

on:
  push:
    branches: [ main, vibe-coding ]
  pull_request:
    branches: [ main ]

# =================================================================
#                      VALIDATION AND QUALITY JOBS
# =================================================================
jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint

  test:
    name: Run Unit Tests
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test

  build:
    name: Build Application
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build

# =================================================================
#                      SECURITY SCAN JOBS
# =================================================================
  sast-scan:
    name: "SAST Scan"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Semgrep SAST scan
        uses: semgrep/semgrep-action@v1
        with:
          config: "p/default"

  sca-scan:
    name: "SCA Scan"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          ignore-unfixed: true
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'

# =================================================================
#                      PUBLISH JOB
# =================================================================
  build-sign-and-publish-image:
    name: Build, Sign, and Publish Image
    needs: [sast-scan, sca-scan]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: Run Trivy vulnerability scanner on image
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          image-ref: 'ghcr.io/${{ github.repository }}:${{ github.sha }}'
          format: 'table'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          exit-code: '0'

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          image: 'ghcr.io/${{ github.repository }}:${{ github.sha }}'
          format: 'spdx-json'
          output-file: 'sbom.spdx.json'
          upload-artifact: true
          upload-artifact-name: 'sbom-${{ github.sha }}'

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign the container image
        run: cosign sign --yes ghcr.io/${{ github.repository }}@${{ steps.docker_build.outputs.digest }}

      - name: Generate SLSA provenance attestation
        uses: actions/attest-build-provenance@v1
        continue-on-error: true
        if: github.repository_owner != '' && !github.event.repository.fork
        with:
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ steps.docker_build.outputs.digest }}
          push-to-registry: true

